### ISSUE TITLE
Compile error under Windows 10

### ISSUE THREAD

**Issue by graphixillusion** [srusso/haystacker#24]
Hi there. I'm getting compiling errors under Windows 10. Here's the log:

```
[ERROR] D:\haystacker\haystacker-server\src\main\kotlin\net\sr89\haystacker\server\HslServer.kt: (35, 55) Cannot access 'toSeconds': it is private in 'Duration'
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for haystacker 1.0-SNAPSHOT:
[INFO]
[INFO] haystacker ......................................... SUCCESS [  1.219 s]
[INFO] haystacker-common .................................. SUCCESS [ 10.849 s]
[INFO] haystacker-server .................................. FAILURE [  6.210 s]
[INFO] haystacker-shell ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.575 s
[INFO] Finished at: 2021-02-07T17:50:26+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.4.21:compile (compile) on project haystacker-server: Compilation failure
[ERROR] D:\haystacker\haystacker-server\src\main\kotlin\net\sr89\haystacker\server\HslServer.kt:[35,55] Cannot access 'toSeconds': it is private in 'Duration'
```

**Comment by srusso** [comment]
Hi @graphixillusion, you need JDK version >= 9 for this project, although personally I'm using 15

**Comment by graphixillusion** [comment]
@srusso you are right, with jdk 15 the compile works good but i got errors when i try to run the server:

java -jar .\haystacker-server-1.0-SNAPSHOT.jar 

no main manifest attribute in .\haystacker-server-1.0-SNAPSHOT.jar

**Comment by srusso** [comment]
This is expected for now, the server jar isn't packaged in a way that it's executable.
So far, I've been running it from IntelliJ, by running this file: `net.sr89.haystacker.server.HslServerKt`

**Comment by srusso** [comment]
I've merged a fix for #25. Could you `git pull`, re-build the project, and try again?

**Comment by graphixillusion** [comment]
@srusso with the last pull, the server runs but the shell doesn't run anymore.

```
java -jar .\haystacker-shell-1.0-SNAPSHOT.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/sr89/haystacker/client/cli/HslShellKt has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

**Comment by srusso** [comment]
Are you using java 8 when running that jar? You can check that by running `java -version`. This project requires a more recent java version, like 15

**Comment by graphixillusion** [comment]
@srusso nope i'm using the same java used when building: openjdk 15

**Comment by srusso** [comment]
Perfect, thanks for the update, so I will close the issue then
